Web/Web/Models/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class TaskViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Uuid { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

        public string Description { get; set; }

        [Required]
        public StudentTaskType TaskType { get; set; }

        [Required]
        public bool Completion { get; set; }

        [Required]
        public int Module { get; set; }

        public List<TaskNoteViewModel> TaskNotes { get; set; }

        public string ParentTask { get; set; }
    }
}

Web/Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Web.Models;

namespace Web.Controllers
{
    public class TaskController : Controller
    {
        private ApplicationUserManager _userManager;

        public TaskController()
        {
        }

        public TaskController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }

            private set
            {
                _userManager = value;
            }
        }

        [HttpGet]
        public ActionResult Index(string semesterId)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        int semid = Int32.Parse(semesterId);
                        var semester = db.StudentSemesters.Include(x => x.Modules.Select(y => y.Tasks)).FirstOrDefault(entity => entity.Id == semid);
                        ICollection<StudentModule> modules = semester.Modules.ToList();
                        ViewBag.Modules = modules;
                        ViewBag.Tasks = modules.First().Tasks.ToList();

                        if (TempData["Message"] != null) ViewBag.Message = TempData["Message"];

                        return View();
                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }

        [HttpGet]
        public ActionResult View(string taskUuid)
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = UserManager.FindById(User.Identity.GetUserId());
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        var task = db.StudentTasks
                            .Include(x => x.TaskNotes)
                            .Include(x => x.Module)
                            .Include(x => x.Module.Semester.ApplicationUser)
                            .FirstOrDefault(x => x.Uuid == taskUuid && x.Module.Semester.ApplicationUser.Id == user.Id);

                        TaskViewModel vTask = new TaskViewModel
                        {
                            Id = task.Id,
                            Uuid = task.Uuid,
                            Name = task.Name,
                            StartDate = task.StartDate,
                            EndDate = task.EndDate,
                            Description = task.Description,
                            TaskType = task.TaskType,
                            Completion = task.Completion,
                            Module = task.Module.Id,
                            ParentTask = task.ParentTask
                        };

                        vTask.TaskNotes = new List<TaskNoteViewModel>();

                        foreach (StudentTaskNote note in task.TaskNotes)
                        {
                            TaskNoteViewModel tn = new TaskNoteViewModel
                            {
                                Id = note.Id,
                                Name = note.Name,
                                Content = note.Content,
                                CreatedDate = note.CreatedDate
                            };
                            vTask.TaskNotes.Add(tn);
                        }

                        var semester = db.StudentSemesters.Include(x => x.Modules.Select(y => y.Tasks)).FirstOrDefault(entity => entity.Id == task.Module.Semester.Id);
                        ICollection<StudentModule> modules = semester.Modules.ToList();
                        ViewBag.Modules = modules;
                        ViewBag.Tasks = modules.First().Tasks.ToList();
                        if (TempData["Message"] != null) ViewBag.Message = TempData["Message"];

                        return View(vTask);
                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }

        [HttpPost]
        public ActionResult Update(TaskViewModel task)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        var taskDb = db.StudentTasks.FirstOrDefault(x => x.Id == task.Id);

                        taskDb.Name = task.Name;
                        taskDb.ParentTask = task.ParentTask;
                        taskDb.StartDate = task.StartDate;
                        taskDb.TaskType = task.TaskType;
                        taskDb.Module = db.StudentModules.FirstOrDefault(x => x.Id == task.Module);
                        taskDb.Completion = task.Completion;
                        taskDb.Description = task.Description;
                        taskDb.EndDate = task.EndDate;

                        db.SaveChanges();

                        TempData["Message"] = "Task has been updated, Click outside the modal to continue";

                        return RedirectToAction("View", "Task", new { taskUuid = task.Uuid });
                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }

        [HttpPost]
        public ActionResult Add(AddTaskViewModel task)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        StudentModule module = db.StudentModules.Include(x => x.Semester).FirstOrDefault(entity => entity.Id == task.Module);
                        StudentTask dbTask = new StudentTask
                        {
                            Name = task.Name,
                            Uuid = Guid.NewGuid().ToString(),
                            StartDate = task.StartDate,
                            EndDate = task.EndDate,
                            Description = task.Description,
                            TaskType = task.TaskType,
                            Completion = false,
                            ParentTask = task.ParentTask,
                            Module = module
                        };

                        db.StudentTasks.Add(dbTask);
                        db.SaveChanges();

                        TempData["Message"] = "Task added, click outside modal to close or add another.";

                        return RedirectToAction("Index", "Task", new { semesterId = module.Semester.Id });
                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }

        [HttpGet]
        public ActionResult ModTasks(string moduleId)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        int modid = Int32.Parse(moduleId);
                        var module = db.StudentModules.Include(x => x.Tasks).FirstOrDefault(entity => entity.Id == modid);
                        List<StudentTask> tasks = module.Tasks.ToList();

                        List<GetModuleTasksAjaxViewModel> viewTasks = new List<GetModuleTasksAjaxViewModel>();

                        foreach (StudentTask t in tasks)
                        {
                            GetModuleTasksAjaxViewModel tvm = new GetModuleTasksAjaxViewModel();
                            tvm.Name = t.Name;
                            tvm.Uuid = t.Uuid;
                            viewTasks.Add(tvm);
                        }

                        return Json(viewTasks, JsonRequestBehavior.AllowGet);
                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }

        [HttpPost]
        public ActionResult Delete(TaskViewModel task)
        {
            if (User.Identity.IsAuthenticated)
            {
                var Uuid = "";
                var user = UserManager.FindById(User.Identity.GetUserId());
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        var dbtask = db.StudentTasks.Include(x => x.TaskNotes).Include(x => x.Module.Tasks).FirstOrDefault(x => x.Id == task.Id);
                        Uuid = dbtask.Uuid;
                        foreach(StudentTaskNote tn in dbtask.TaskNotes.ToList())
                        {
                            db.StudentTaskNotes.Remove(tn);
                        }

                        foreach(StudentTask t in dbtask.Module.Tasks)
                        {
                            if(t.ParentTask == dbtask.Uuid)

Web/Web/Controllers/TaskNoteController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using System.Data.Entity;

namespace Web.Controllers
{
    public class TaskNoteController : Controller
    {
        private ApplicationUserManager _userManager;

        public TaskNoteController()
        {
        }

        public TaskNoteController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }

            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index(string taskId)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        ViewBag.TaskId = taskId;
                        if (TempData["Message"] != null) ViewBag.Message = TempData["Message"];
                        return View();
                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }
            return new HttpUnauthorizedResult();
        }

        [HttpGet]
        public ActionResult View(string noteId)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        int nid = Int32.Parse(noteId);
                        StudentTaskNote n = db.StudentTaskNotes.FirstOrDefault(x => x.Id == nid);
                        TaskNoteViewModel nvm = new TaskNoteViewModel
                        {
                            Id = n.Id,
                            Name = n.Name,
                            Content = n.Content,
                        };

                        ViewBag.NoteId = noteId;

                        if(TempData["Message"] != null) ViewBag.Message = TempData["Message"];
                        return View(nvm);
                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }
            return new HttpUnauthorizedResult();
        }

        [HttpPost]
        public ActionResult Add(TaskNoteViewModel note)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        StudentTask task = db.StudentTasks.FirstOrDefault(x => x.Id == note.TaskId);

                        StudentTaskNote t = new StudentTaskNote
                        {
                            Name = note.Name,
                            Uuid = Guid.NewGuid().ToString(),
                            CreatedDate = DateTime.Now,
                            Task = task,
                            Content = note.Content
                        };
                        db.StudentTaskNotes.Add(t);
                        db.SaveChanges();

                        TempData["Message"] = "Note succesfully added to task, Click outside modal to exit or add another note.";

                        return RedirectToAction("View", "Task", new { taskUuid = task.Uuid });

                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }

        [HttpPost]
        public ActionResult Update(TaskNoteViewModel note)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        StudentTaskNote tasknote = db.StudentTaskNotes.Include(x => x.Task).FirstOrDefault(x => x.Id == note.Id);

                        tasknote.Name = note.Name;
                        tasknote.Content = note.Content;
                        db.SaveChanges();

                        TempData["Message"] = "Note succesfully updated, Click outside modal to exit";

                        return RedirectToAction("View", "Task", new { taskUuid = tasknote.Task.Uuid });

                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }

        [HttpPost]
        public ActionResult Delete(TaskNoteViewModel task)
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    try
                    {
                        StudentTaskNote tasknote = db.StudentTaskNotes.Include(x => x.Task).FirstOrDefault(x => x.Id == task.Id);
                        var tUuid = tasknote.Task.Uuid;

                        db.StudentTaskNotes.Remove(tasknote);
                        db.SaveChanges();

                        TempData["Message"] = "Note succesfully deleted, Click outside modal to exit";

                        return RedirectToAction("View", "Task", new { taskUuid = tUuid });

                    }
                    catch
                    {
                        return new HttpNotFoundResult();
                    }
                }
            }

            return new HttpUnauthorizedResult();
        }
    }
}

Web/Web/Views/Task/View.cshtml
@model Web.Models.TaskViewModel
@{ Layout = "~/Views/Shared/modalLayout.cshtml"; }

@using (Html.BeginForm("Update", "Task", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    <h4>View Task</h4>
    <hr />
    <div class="row" id="taskform">
        <div class="col-md-6" style="padding-top:3px">
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Uuid)
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.StartDate, "{0:yyyy-MM-dd HH:mm}", new { @class = "date", autocomplete ="off" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.EndDate, "{0:yyyy-MM-dd HH:mm}", new { @class = "date", autocomplete = "off" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Description, 6, 40, new { @class = "form-control" })
                </div>
            </div>
            @Html.ValidationSummary("", new { @class = "text-danger" })

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.TaskType, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(m => m.TaskType,
                        "Select Task Type",
                        new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Module, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.Module, new SelectList(ViewBag.Modules, "Id", "Name"), new { @class = "modules, form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ParentTask, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.ParentTask, new SelectList(ViewBag.Tasks, "Uuid", "Name"), new { @class = "tasks, form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Completion, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(m => m.Completion, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10" style=" padding-left:25%; padding-top:25px">
                    <input type="submit" class="btn btn-default" value="Update Task" />
                </div>
            </div>
            <h5>@ViewBag.Message</h5>
        </div>
    </div>
}

<div class="row">
    <div class="col-md-6 border">
        <h6>Notes</h6>
        <div class="vertical-menu">
            <a href="@Url.Action("Index", "TaskNote", new { TaskId = Model.Id })">Create New Note</a>
            @foreach (var t in Model.TaskNotes)
            {
                <a href="@Url.Action("View", "TaskNote", new { noteId = t.Id })">@t.Name</a>
            }
        </div>
    </div>
        
    <div class="col-md-6">
        @using (Html.BeginForm("Delete", "Task", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", @id = "taskDeleteBtn" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <div class="col-md-10" style="padding-top:25px">
                    <input type="submit" class="delete-btn btn btn-default" value="Delete Task" />
                </div>
            </div>
        }
    </div> 
</div>

        <script>
    $(document).ready(function () {
        if ("@Model.ParentTask" == "") {
            $('#ParentTask').append('<option selected value=""> No parent </option>');
        } else {
            $('#ParentTask').append('<option value=""> No parent </option>');
        }
    });

    $('#Module').change(function () {
        $.ajax({
            type: "GET",
            url: "@Url.Action("ModTasks", "Task")" + "?moduleId=" + $('#Module').val(),
            dataType: "json",
            success: function (data) {
                $('#ParentTask').empty();
                $('#ParentTask').append('<option value=""> No parent </option>');
                for (var entry in data) {
                    $('#ParentTask').append(
                        '<option value="'
                        + data[entry].Id + '">'
                        + data[entry].Name + '</option>'
                    );
                }
            }
        });
    });
        </script>


        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Web/Web/Views/Task/index.cshtml
@model Web.Models.AddTaskViewModel
@{ Layout = "~/Views/Shared/modalLayout.cshtml"; }

@using (Html.BeginForm("Add", "Task", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    <h4>Create a new Task</h4>
    <hr />
    <div class="row" id="taskform">
        <div class="col-md-6" style="padding-top:3px">
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.StartDate, "{0:yyyy-MM-dd HH:mm}", new { @class = "date", autocomplete = "off" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.EndDate, "{0:yyyy-MM-dd HH:mm}", new { @class = "date", autocomplete = "off" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Description, 6, 40, new { @class = "form-control" })
                </div>
            </div>
            @Html.ValidationSummary("", new { @class = "text-danger" })

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.TaskType, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(m => m.TaskType,
                        "Select Task Type",
                        new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Module, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.Module, new SelectList(ViewBag.Modules, "Id", "Name"), new { @class = "modules, form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ParentTask, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.ParentTask, new SelectList(ViewBag.Tasks, "Uuid", "Name"), new { @class = "tasks, form-control" })
                </div>
            </div>
            <h5>@ViewBag.Message</h5>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="padding-left:25%; padding-top:25px">
                    <input type="submit" class="btn btn-default" value="Create Task" />
                </div>
            </div>
        </div>

    </div>


    <script>
        $(document).ready(function () {
            $('#ParentTask').append('<option selected value=""> No parent </option>');
        });

        $('#Module').change(function () {
            $.ajax({
                type: "GET",
                url: "@Url.Action("ModTasks", "Task")" + "?moduleId=" + $('#Module').val(),
                dataType: "json",
                success: function (data) {
                    $('#ParentTask').empty();
                    $('#ParentTask').append('<option value=""> No parent </option>');
                    for (var entry in data) {
                        $('#ParentTask').append(
                            '<option value="'
                            + data[entry].Id + '">'
                            + data[entry].Name + '</option>'
                        );
                    }
                }
            });
        });
    </script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}