Web/Web/Controllers/DashboardController.cs
namespace Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Script.Serialization;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.Owin;
    using Web.Models;
    using System.Data.Entity;

    public class DashboardController : Controller
    {
        private ApplicationUserManager _userManager;

        public DashboardController()
        {
        }

        public DashboardController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }

            private set
            {
                _userManager = value;
            }
        }

        // GET: Dashboard
        [HttpGet]
        public ActionResult Index(string semesterId)
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = UserManager.FindById(User.Identity.GetUserId());
                try
                {
                    var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>();

                    int semid = Int32.Parse(semesterId);
                    ViewBag.SemId = semid;
                    StudentSemester semester = db.StudentSemesters.Include(x => x.Modules.Select(y => y.Tasks)).Include(x => x.ApplicationUser).FirstOrDefault(entity => entity.Id == semid);
                    if (semester.ApplicationUser.Id != user.Id) return new HttpUnauthorizedResult();
                    ICollection<StudentModule> modules = semester.Modules;
                    LinkedList<StudentTask> tasks = new LinkedList<StudentTask>();

                    ViewBag.Title = semester.SemesterName + " Dashboard";
                    ViewBag.mods = semester.Modules.ToList();
                    foreach (StudentModule m in modules)
                    {
                        foreach (StudentTask t in m.Tasks)
                        {
                            tasks.AddLast(t);
                        }
                    }

                    var ganttList = new List<GanttTask>();
                    var parentList = new List<string>();
                    foreach (StudentTask t in tasks)
                    {
                        if (t.ParentTask != string.Empty)
                        {
                            parentList.Add(t.ParentTask);
                        }

                        var type = "error";
                        switch (t.TaskType)
                        {
                            case StudentTaskType.ACTIVITY:
                                type = "bar-activity";
                                break;
                            case StudentTaskType.COURSEWORK:
                                type = "bar-coursework";
                                break;
                            case StudentTaskType.LAB:
                                type = "bar-lab";
                                break;
                            case StudentTaskType.LECTURE:
                                type = "bar-lecture";
                                break;
                            case StudentTaskType.MILESTONE:
                                type = "bar-milestone";
                                break;
                            case StudentTaskType.SEMINAR:
                                type = "bar-seminar";
                                break;
                            default:
                                break;
                        }

                        ganttList.Add(new GanttTask
                        {
                            start = t.StartDate.ToString("yyyy-MM-dd"),
                            end = t.EndDate.ToString("yyyy-MM-dd"),
                            name = t.Name,
                            id = t.Uuid,
                            progress = " ",
                            dependencies = t.ParentTask,
                            custom_class = type,
                            type = t.TaskType.ToString(),
                            module = t.Module.Name,
                            completed = t.Completion.ToString()
                        });
                    }

                    foreach (GanttTask t in ganttList)
                    {
                        foreach (string p in parentList)
                        {
                            if (t.id == p)
                            {
                                t.progress = "100";
                                if (!t.custom_class.Contains("-parent"))
                                {
                                    t.custom_class += "-parent";
                                }
                            }
                        }
                    }

                    return View(ganttList);
                }
                catch
                {
                    return new HttpNotFoundResult();
                }
            }
            return new HttpUnauthorizedResult();
        }

        [HttpPost]
        public ActionResult UpdateTaskDates(GanttTask tsk)
        {
            try
            {
                var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
                var task = db.StudentTasks.First(a => a.Uuid == tsk.id);
                DateTime.TryParse(tsk.start, out DateTime sd);
                task.StartDate = sd;
                DateTime.TryParse(tsk.end, out DateTime ed);
                task.EndDate = ed;
                db.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(new
                {
                    ResultValue = "An Exception Occured: " + e.Message
                });
            }
            return Json(new
            {
                ResultValue = "Task Date Updated"
            });
        }

        [HttpGet]
        public JsonResult getNotesList(string moduleId)
        {
            try
            {
                Int32.TryParse(moduleId, out int modId);

                var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
                StudentModule module = db.StudentModules.Include(x => x.ModuleNotes).FirstOrDefault(entity => entity.Id == modId);
                List<StudentModuleNoteViewModel> notes = new List<StudentModuleNoteViewModel>();

                foreach (StudentModuleNote n in module.ModuleNotes)
                {
                    StudentModuleNoteViewModel mnote = new StudentModuleNoteViewModel();
                    mnote.Id = n.Id;
                    mnote.Name = n.Name;
                    notes.Add(mnote);
                }

                return Json(
                    notes,
                    JsonRequestBehavior.AllowGet
                );
            }
            catch(Exception e)
            {
                return Json(new
                {
                    ResultValue = "An error occured: " + e.Message
                });
            }
        }
    }
}

Web/Web/Controllers/HomeController.cs
namespace Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Xml.Linq;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.Owin;
    using Web.Models;
    using System.Data.Entity;

    public class HomeController : Controller
    {
        private ApplicationUserManager _userManager;

        public HomeController()
        {
        }

        public HomeController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }

            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>())
                {
                    var user = UserManager.FindById(User.Identity.GetUserId());
                    ViewBag.UserNow = user;

                    var semesters = db.StudentSemesters.Include("ApplicationUser").Where(s => s.ApplicationUser.Id == user.Id).ToList<StudentSemester>();

                    if (semesters != null)
                    {
                        return View(semesters.ToList());
                    }
                    return View();
                }
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult CreateSemesterModal()
        {
            if (TempData["Message"] != null) ViewBag.Message = TempData["Message"];
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendContactForm(Models.ContactModel mod)
        {
            //Web.Models.ContactModel c = new Web.Models.ContactModel(mod.name, mod.email, mod.message);
            //Need to provide feedback.
            TempData["cfResult"] = mod.sendEmail();
            return RedirectToAction("Contact");
        }


        [HttpPost]
        public ActionResult UploadSemesterFile(CreateSemesterViewModel input)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());

            if (input.File != null && input.File.ContentLength > 0)
            {
                try
                {
                    System.IO.StreamReader sr = new System.IO.StreamReader(input.File.InputStream);

                    XDocument doc = XDocument.Load(sr);
                    var reader = doc.CreateReader();
                    var db = HttpContext.GetOwinContext().Get<ApplicationDbContext>();

                    StudentSemester semester = new StudentSemester
                    {
                        StartDate = input.StartDate,
                        EndDate = input.EndDate,
                        SemesterName = input.Name,
                        ApplicationUser = user
                    };
                    db.StudentSemesters.Add(semester);

                    if (reader.ReadToDescendant("UserModules"))
                    {
                        if (reader.ReadToDescendant("module"))
                        {
                            do
                            {
                                StudentModule module = new StudentModule
                                {
                                    Uuid = reader.GetAttribute("uuid"),
                                    Name = reader.GetAttribute("name"),
                                    StartDate = DateTime.Parse(reader.GetAttribute("startDate")),
                                    EndDate = DateTime.Parse(reader.GetAttribute("endDate")),
                                    ModuleCode = reader.GetAttribute("moduleCode"),
                                    ModuleOrganiser = reader.GetAttribute("moduleOrganiser"),
                                    CourseworkAmount = float.Parse(reader.GetAttribute("courseworkAmount")),
                                    Exam = bool.Parse(reader.GetAttribute("exam")),
                                    Semester = semester
                                };

                                var moduleTest = db.StudentModules.Include(x => x.Semester.ApplicationUser).FirstOrDefault(x => x.Uuid == module.Uuid 
                                    && x.Semester.ApplicationUser.Id == user.Id);
                                if (moduleTest != null)
                                {
                                    throw new Exception("This file has already been imported!");
                                }

                                db.StudentModules.Add(module);

                                if (reader.ReadToDescendant("ModuleNotes"))
                                {
                                    if (reader.ReadToDescendant("note"))
                                    {
                                        do
                                        {
                                            StudentModuleNote note = new StudentModuleNote
                                            {
                                                Uuid = reader.GetAttribute("uuid"),
                                                Name = reader.GetAttribute("name"),
                                                Content = reader.GetAttribute("text"),
                                                CreatedDate = DateTime.Now,
                                                Module = module
                                            };
                                            db.StudentModuleNotes.Add(note);
                                        } while (reader.ReadToNextSibling("note"));
                                    }
                                }

                                if (reader.ReadToFollowing("ModuleTasks"))
                                {
                                    if (reader.ReadToDescendant("task"))
                                    {
                                        do
                                        {
                                            StudentTask task = new StudentTask
                                            {
                                                Uuid = reader.GetAttribute("uuid"),
                                                Name = reader.GetAttribute("name"),
                                                StartDate = DateTime.Parse(reader.GetAttribute("startDate")),
                                                EndDate = DateTime.Parse(reader.GetAttribute("endDate")),
                                                Description = reader.GetAttribute("description"),
                                                Completion = bool.Parse(reader.GetAttribute("completion")),
                                                TaskType = (StudentTaskType)Enum.Parse(typeof(StudentTaskType), reader.GetAttribute("type")),
                                                Module = module,
                                                ParentTask = reader.GetAttribute("parent")
                                            };
                                            db.StudentTasks.Add(task);

                                            if (reader.ReadToDescendant("TaskNotes")) {
                                                if (reader.ReadToDescendant("note")) {
                                                    do
                                                    {
                                                        StudentTaskNote note = new StudentTaskNote
                                                        {
                                                            Uuid = reader.GetAttribute("uuid"),
                                                            Name = reader.GetAttribute("name"),
                                                            Content = reader.GetAttribute("text"),
                                                            CreatedDate = DateTime.Now,
                                                            Task = task
                                                        };
                                                        db.StudentTaskNotes.Add(note);
                                                    } while (reader.ReadToNextSibling("note"));
                                                    reader.ReadEndElement();
                                                }
                                            }
                                        } while (reader.ReadToNextSibling("task"));

                                        reader.ReadEndElement();
                                    }
                                }

                            } while (reader.ReadToNextSibling("module"));

                        }
                    }

                    db.SaveChanges();
                }
                catch (Exception ex) {
                    TempData["Message"] = "ERROR:" + ex.Message.ToString();
                    return RedirectToAction("createSemesterModal", "Home");
                }
            } else {
                TempData["Message"] = "You have not specified a file.";
            }

            TempData["Message"] = "Success! upload another semester or click outside this window to close";

            return RedirectToAction("createSemesterModal", "Home");
        }
    }
}

Web/Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "Help";
}
<div class="jumbotron">

    <h2>@ViewBag.Title</h2>

    <h3>About Us</h3>
    <p>My Plan was created for the 2019 CMP-5012B Software Engineering Summative Assignment 2. This appliction forms Group 12s submission, and is the combined works of 100166648, 100168172, 100177699, 100184794, 100203707.</p>

    <h3>Features</h3>
    <ul>
        <li>Load Semester File - To create a semester study profile, a file will be required from your academic hub in the XML format.</li>
        <li>Add Tasks - Add tasks to your modules</li>
        <li>Notes - Add notes to your modules and tasks</li>
        <li>Dependencies - Tasks can have subtasks</li>
        <li>Gantt Chart - Visualise tasks on a Gantt Chart, to enable time planning.</li>
    </ul>


    <h3>Using The Semester Dashboard</h3>
    <h5>Add a Task</h5>
    <div class="helpItem">
        <table>
            <tr>
                <td>
                    <img src="~/Content/newTask.png" alt="Image of task drag handles" />
                </td>
                <td>
                    To add a task, click the Add Task button at the bottom of the chart, and then fill in the task details. 
                    Your task will now appear on the Gantt Chart.
                </td>
            </tr>
        </table>
    </div>


    <h5>Modifying Tasks</h5>
    <div class="helpItem">
        <table>
            <tr>
                <td>
                    <img src="~/Content/taskDrag.png" alt="Image of task drag handles" />
                </td>
                <td>
                    To change the start or end date of a task, or to move its timeframe all together, simply drag either end or the whole task.
                    See the lock button below to disable this.
                </td>
            </tr>

            <tr>
                <td>
                    <img src="~/Content/viewTask.png" alt="Image of task view popup." />
                </td>
                <td>
                    To change more information about the task, click on a task, which will launch the view task popup. From here you
                    can change details about the task.
                </td>
            </tr>
        </table>
    </div>

    <h5>Filtering Tasks</h5>
    <div class="helpItem">
        <table>
            <tr>
                <td>
                    <img src="~/Content/filterType.png" alt="Image of task type filter drop down menu" />
                </td>
                <td>
                    To Filter by task type, use the drop down menu and select a task type to display.
                </td>
            </tr>

            <tr>
                <td>
                    <img src="~/Content/filterModule.png" alt="Image of module selection buttons" />
                </td>
                <td>
                    To Filter by module, select the desired module from the buttons below the Gantt Chart.
                </td>
            </tr>

            <tr>
                <td>
                    <img src="~/Content/taskCompletion.png" alt="Image of task completion filter" />
                </td>
                <td>
                    To Filter by completion status, select from the drop down box the desired completion. <br />
                    In Progress: Tasks that have not been completed, and have not been missed. <br />
                    Upcoming: Tasks that have not been completed, and have are due within the next 2 weeks.<br />
                    Completed: Tasks that have been completed.<br />
                    Missed: Tasks past their due date that have not been completed.<br />
                </td>
            </tr>
        </table>
    </div>



    <h5>Lock Button</h5>
    <div class="helpItem">
        <table>
            <tr>
                <td>
                    <img src="~/Content/lockHelp.png" alt="Image of Lock button" />
                </td>
                <td>
                    If you would like to lock interactive changing on task duration, start date, or end date, press the lock button
                    to toggle drag locking. To unlock, simply press the button again.
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    Hint: This may be helpful on touchscreen devices.
                </td>
            </tr>
        </table>
    </div>




</div>

Web/Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}



<div class="jumbotron">
    <h2>@ViewBag.Title</h2>

    <address>
        School of Computing Sciences<br />
        University of East Anglia<br />
        Norwich Research Park<br />
        NR4 7TJ
    </address>


    @using (Html.BeginForm("SendContactForm", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @model Web.Models.ContactModel
        <h4>Contact Us</h4>
        @TempData["cfResult"]
        <hr />
        <div class="form-group">
            <label>Name:</label>
            <div class="col-md-10">
                <input type="text" size="50" name="name" id="name" title="Name" /><br><br>
            </div>
        </div>
        <div class="form-group">
            <label>Email:</label>
            <div class="col-md-10">
                <input type="text" size="50" name="email" id="email" title="Email"/><br><br>
            </div>
        </div>
        <div class="form-group">
            <label >Message:</label>
            <div class="col-md-10">
                <textarea rows="5" cols="50" name="message" title="Message to MyPlan Team."></textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Send" title="Submit"/>
            </div>
        </div>
    }
</div>

Web/Web/Views/Home/CreateSemesterModal.cshtml
@model Web.Models.CreateSemesterViewModel
@{ Layout = "~/Views/Shared/modalLayout.cshtml"; }

@using (Html.BeginForm("UploadSemesterFile", "Home", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", @id="sem-upload"}))
{
    @Html.AntiForgeryToken()
    <h4>Create a new Semester</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.StartDate, new { @class = "date form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EndDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EndDate, new { @class = "date form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.File, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.File, new { @class = "form-control" })
        </div>
    </div>
    <h5>@ViewBag.Message</h5>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" id="createSemButton" style=" padding-left:34%; padding-top:25px">
            <input type="submit" class="btn btn-default" value="Create Semester" />
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        $('#File').attr("type", "file");
        $('#File').attr("class", "");
    });
</script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Web/Views/Home/Index.cshtml
@model IEnumerable<Web.Models.StudentSemester>

    @{
    ViewBag.Title = "Home Page";
    }

    @if (ViewBag.UserNow != null)
    {
    <div class="jumbotron">
        <h1>Semester Selection</h1>
        <p class="lead">Select a semester, or upload a new file from your Hub.</p>
        @if (Model != null)
        {
            foreach (var s in Model)
            {
                <p>
                    <button class="semButton" onclick="location.href='@Url.Action("Index", "Dashboard", new { semesterId = s.Id })'">
                        @s.SemesterName
                    </button>
                </p>
            }
        }
        <button class="semButton" id="newSemButton"> Create New Semester </button> @*Create a new Semester Modal*@
        <script>
            $('#newSemButton').click(function (e) {
                var src = "@Url.Action("createSemesterModal", "Home")";
                $.modal('<iframe src="' + src + '" height="530" width="500" style="border:0; border-radius: 15px;">', {
                    closeHTML: "",
                    overlayCss: {
                        backgroundColor: "black",
                        opacity: 0.5,
                    },
                    containerCss: {
                        backgroundColor: "#EAEBED",
                    },
                    overlayCss: {
                        backgroundColour: "#000000"
                    },
                    overlayClose: true,
                    onClose : function(dialog) {
                        window.location.reload();
                    }
                });

                return false;
            });
        </script>
    </div>
    }
    else
    {
    <div class="jumbotron">
        <h1>Welcome</h1>
        <p class="lead">My Plan is a revolutionary new study planning solution, to allow you to manage your time better and achieve higher grades. My Plan allows you to add tasks, see what tasks are coming up, visualise your workload with a Gantt Chart, and much more. To sign up, hit the button below.</p>
        <p><a href="/Account/Register" class="btn btn-default">Register &raquo;</a></p>
    </div>

    /*<div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div> */
    }